/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polygon_perimeter_calc;

import java.awt.Component;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.DefaultListModel;

/**
 *
 * @author oscar
 */
public class GUI_POLY extends javax.swing.JFrame {

    /**
     * Creates new form GUI_POLY
     */
    Point punto;
    private DefaultListModel datalist;
    int x,y;
    int indexlist=0;
    public GUI_POLY() {
        this.process = new Process();
        datalist = new DefaultListModel();
        initComponents();
        
    }
    Process process ;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfY = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        bErase = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bADD = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfResult = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        bCalc = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bGraph = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_Vertexs = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jPanel4.setLayout(new java.awt.GridLayout(3, 1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Vertice:");
        jPanel4.add(jLabel3);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 1, 0));

        jLabel1.setLabelFor(tfX);
        jLabel1.setText("Cordenada X");
        jPanel1.add(jLabel1);
        jPanel1.add(tfX);

        jLabel2.setLabelFor(tfY);
        jLabel2.setText("Cordenada Y");
        jPanel1.add(jLabel2);
        jPanel1.add(tfY);

        jPanel4.add(jPanel1);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        bErase.setText("Borrar");
        bErase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEraseMouseClicked(evt);
            }
        });
        jPanel5.add(bErase);
        jPanel5.add(jLabel4);

        bADD.setText("Agregar");
        bADD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bADDMouseClicked(evt);
            }
        });
        jPanel5.add(bADD);

        jPanel4.add(jPanel5);

        jPanel7.add(jPanel4);

        jPanel9.setLayout(new java.awt.GridLayout(3, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Perimetro");
        jPanel9.add(jLabel6);

        tfResult.setEditable(false);
        tfResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultActionPerformed(evt);
            }
        });
        jPanel9.add(tfResult);

        jPanel11.setLayout(new java.awt.GridLayout(1, 3));

        bCalc.setText("Calcular");
        bCalc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bCalcMouseClicked(evt);
            }
        });
        bCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcActionPerformed(evt);
            }
        });
        jPanel11.add(bCalc);
        jPanel11.add(jSeparator1);

        bGraph.setText("Graficar");
        jPanel11.add(bGraph);

        jPanel9.add(jPanel11);

        jPanel7.add(jPanel9);

        jPanel6.add(jPanel7);

        jScrollPane1.setViewportView(list_Vertexs);

        jLabel5.setText("Lista de vertices");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Calculadora", jPanel2);

        canvas1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GUI", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultActionPerformed

    private void bCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCalcActionPerformed

    private void bEraseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEraseMouseClicked
        // TODO add your handling code here:
        process.P.eeraseLastVertex();
        datalist.remove(indexlist);
        indexlist--;
    }//GEN-LAST:event_bEraseMouseClicked

    private void bADDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bADDMouseClicked
        // TODO add your handling code here:
       
        if(process.addNewData( tfX.getText() , tfY.getText() ))
        {
        String vertice = "X: ".concat(tfX.getText()).concat(" Y: ").concat(tfY.getText());
        datalist.addElement(vertice);
        indexlist++;
        list_Vertexs.setModel(datalist);
        }
    }//GEN-LAST:event_bADDMouseClicked

    private void bCalcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalcMouseClicked
        // TODO add your handling code here:
        tfResult.setText(process.printResult());
    }//GEN-LAST:event_bCalcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_POLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_POLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_POLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_POLY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_POLY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bADD;
    private javax.swing.JButton bCalc;
    private javax.swing.JButton bErase;
    private javax.swing.JButton bGraph;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> list_Vertexs;
    private javax.swing.JTextField tfResult;
    private javax.swing.JTextField tfX;
    private javax.swing.JTextField tfY;
    // End of variables declaration//GEN-END:variables
}
